# File: azure-pipelines.yml
name: Azure Pipelines
variables:
  python.version: '3.7.6'
  trigger: ops

stages: 
- stage: Provision
  jobs:
  - job: provision_azure_resources
    displayName: Provision Azure resources
    pool: Default 
    steps:
    - task: DownloadSecureFile@1
      name: variable_definitions
      displayName: Download terraform.tfvars
      inputs:
        secureFile: 'terraform.tfvars' 
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'AAAAB3NzaC1yc2EAAAADAQABAAABgQCdN9QtteLLWNpGh3ulIaWEe5WSXDaQOzWBR3kD5Fdbk3zMdJEnS6cYoveb0U1cFBT1fNq1iZc4mukpt7IDUNp78R4s6MRnWztMXnbaF9ZesS4jHMpgfRB/KQNvD4mwPO+HjfLHHHCtVOoYzFH9O6sMQdH2krclIWmAyqY/KXPNTAdlEg5BAPKH7FXT0hr300nYa8fNrCUzO6kVqU4tqLjDNX/xISri2YDIB4DuOmLnZIEEeCpMFCAtI1Bz964dLzzW+JgoOrTcqP+Y8BPw0Lz2eo17w5T+37MdUTOA9wdafJoH6pODczAiTGw/2FFB0YEgxe7OZVU+CIxMexBLDFEbjpRhztOOVwVuPeYARyYaoS3KpndyhxWWJMHNRZ5k4b7zk1xnFedYeTpP0Ii0cE/m3+ebiBCL2HcPdEUXHDGzhQVJFR/sLwMZVu9kLk94GDifo1DvTItmKKJe9Icfz5+VtauoiD69xnw709qciyES40tUax9lcZYgeJuAN7YSA+s='
        sshPublicKey: $(myPubKey)
        sshKeySecureFile: 'id_rsa'

    # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    #   displayName: 'Install Terraform 1.0.0'
    #   inputs:
    #     terraformVersion: '1.0.0'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test' 

    - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '0.15.0'
            
    - task: TerraformTaskV2@2
      displayName: 'Terraform : Initialization'
      inputs:
        provider: "azurerm"
        backendType: 'azurerm'
        command: 'init'
        commandOptions: |
          -reconfigure        
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'                
        backendServiceArm: 'arm-servicon'
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: 'tstate1096'
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'terraform.tfstate'

    - task: CopyFiles@2
      displayName: 'Prepare files for publish'
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)/terraform/environments/test
        Contents: |
          **
          !**\.terraform\** 
        TargetFolder: '$(Build.StagingDirectory)'

    # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
    #   displayName: 'Terraform : Validation'
    #   inputs:
    #     command: validate
    #     workingDirectory: '/home/azureuser/myagent/_work/_tasks'     

    # - task: TerraformTaskV1@0
    #   displayName: Terraform Init
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'init'
    #     workingDirectory: '$(terraformWorkingDirectory)/terraform/environments/test'                
    #     backendServiceArm: 'arm-servicon'
    #     backendAzureRmResourceGroupName: 'tstate'
    #     backendAzureRmStorageAccountName: 'tstate1096'
    #     backendAzureRmContainerName: 'tstate'
    #     backendAzureRmKey: 'terraform.tfstate'
        
    - task: TerraformTaskV1@0
      displayName: Run `terraform apply`
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: |
          -auto-approve
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
        environmentServiceNameAzureRM: 'arm-servicon'

- stage: Build
  jobs:
  - job: build_artifacts
    displayName: Build artifacts
    pool: Default 
    steps: 
    - task: ArchiveFiles@2
      displayName: Archive FakeRestAPI
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automated-testing/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/fakerestapi-$(Build.BuildId).zip'
        verbose: true
    - task: PublishPipelineArtifact@1
      displayName: Publish FakeRestAPI artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/fakerestapi-$(Build.BuildId).zip'
        artifactName: 'fakerestapi-atf'
    - task: ArchiveFiles@2
      displayName: Archive Selenium
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automated-testing/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/selenium-$(Build.BuildId).zip'
        verbose: true
    - task: PublishPipelineArtifact@1
      displayName: Publish Selenium artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/selenium-$(Build.BuildId).zip'
        artifactName: 'selenium-atf'

- stage: Deployment
  jobs:
  - deployment: deployment_fakerestapi
    displayName: Deploy FakeRestAPI
    pool: Default
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: Deploy Azure WebApp
            inputs:
              azureSubscription: 'arm-servicon'
              appName: 'quality-releases-appservice'
              appType: 'quality-releases'
              package: $(Pipeline.Workspace)/fakerestapi-atf/fakerestapi-$(Build.BuildId).zip
              deploymentMethod: zipDeploy
  - deployment: deploy_to_vm
    displayName: Deploy_app_to_virtual_machine
    environment:
      name: 'TEST'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
          
              #! /bin/bash
              sudo apt update
              sudo apt install software-properties-common -y
              sudo apt-add-repository ppa:universe -y
              sudo apt-get update
              sudo apt-get install python3-pip -y
              sudo apt-get install zip unzip -y
              sudo apt-get install -y chromium-browser
              sudo apt-get install -y chromium-chromedriver
              python3 -m pip install --upgrade pip
              pip3 install selenium
              python3 -c "import selenium; print('Selenium Version:', selenium.__version__)"
                 
- stage: Test
  jobs:
  - deployment: test_machine
    displayName: Test VM
    environment:
      name: 'TEST'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: |
              cd $(Pipeline.Workspace)/selenium-atf
              find . -type f ! -name 'selenium-$(Build.BuildId).zip' -delete  # delete everything except 'selenium-$(Build.BuildId).zip'
              unzip -o selenium-$(Build.BuildId).zip
              sudo mkdir -p /var/log/selenium
              sudo chmod 664 /var/log/selenium
              sudo python3 -u selenium-test.py 2>&1 | sudo tee -a /var/log/selenium/selenium-test.log
              cd $(System.DefaultWorkingDirectory)
              mkdir -p log/selenium
              sudo cp /var/log/selenium/selenium-test.log log/selenium/selenium-test.log
            displayName: Run Selenium tests
          - task: PublishPipelineArtifact@1
            displayName: Publish logs from Selenium
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/log/selenium/selenium-test.log'
              artifactName: 'selenium-logs-atf'
  - job: jmeter_test
    displayName: Test JMeter
    pool: Default
    steps:
    - bash: |
        sudo apt-get install openjdk-11-jre-headless -y
        java -version
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.tgz -O jmeter.tgz
        tar xzvf jmeter.tgz
        apache-jmeter-5.4/bin/jmeter --version2.66.0
        mkdir -p log/jmeter
      displayName: Install JMeter
    - bash: |
        apache-jmeter-5.4/bin/jmeter -n -t automated-testing/jmeter/stress-test.jmx \
                                    -l log/jmeter/stress-test-result.csv \
                                    -e -f -o log/jmeter/stress-test-html-report \
                                    -j log/jmeter/jmeter-stress-test.log
      displayName: JMeter stress test
    - bash: |
        apache-jmeter-5.4/bin/jmeter -n -t automated-testing/jmeter/endurance-test.jmx \
                                    -l log/jmeter/endurance-test-result.csv \
                                    -e -f -o log/jmeter/endurance-test-html-report \
                                    -j log/jmeter/jmeter-endurance-test.log
      displayName: JMeter endurance test
    - task: ArchiveFiles@2
      displayName: Archive JMeter stress test HTML report
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/log/jmeter/stress-test-html-report'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/log/jmeter/stress-test-html-report-$(Build.BuildId).zip'
        verbose: true
    - task: ArchiveFiles@2
      displayName: Archive JMeter endurance test HTML report
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/log/jmeter/endurance-test-html-report'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/log/jmeter/endurance-test-html-report-$(Build.BuildId).zip'
        verbose: true
    - bash: |
        rm -rf log/jmeter/stress-test-html-report
        rm -rf log/jmeter/endurance-test-html-report
        cd log/jmeter
        displayName: Delete initial JMeter HTML test reports
    - task: PublishPipelineArtifact@1
      displayName: Publish JMeter logs
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/log/jmeter'
        artifactName: 'jmeter-logs-atf'
  - job: newman_test
    displayName: Test Postman with Newman
    pool: Default
    steps: 
      - task: NodeTool@0
        displayName: Install Node v12.X
        inputs:
          versionSpec: '12.x'
      - bash: |
          npm install -g newman
          newman --version
          mkdir -p log/newman79f93199-ea71-4fc7-a0c1-a0f75c5ea7e1
        displayName: Install Newman
      - bash: |
          newman run automated-testing/postman/regression-test.json \
                    --reporters cli,junit \
                    --reporter-junit-export log/newman/regression-test.xml \
                    --suppress-exit-code
        displayName: Newman regression test
      - bash: |
          newman run automated-testing/postman/validation-test.json \
                    -e automated-testing/postman/validation-test-env.postman-environment.json \
                    --reporters cli,junit \
                    --reporter-junit-export log/newman/validation-test.xml \
                    --suppress-exit-codazurerm_network_interface.test.ide
          ls -la $(System.DefaultWorkingDirectory)/log/newman/
        displayName: Newman validation test
      - task: PublishPipelineArtifact@1
        displayName: Publish Newman logs
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/log/newman'
          artifactName: 'drop-newman-logs'
      - task: PublishTestResults@2
        displayName: 'Publish Newman test results'
        inputs:
          testRunner: 'JUnit'
          searchFolder: '$(System.DefaultWorkingDirectory)/log/newman'
          testResultsFiles: '*.xml'
          mergeTestResults: true
          testRunTitle: 'Publish Newman test results'
